_wandb:
    value:
        cli_version: 0.23.1
        e:
            n0jzqf4dz2jyki3iesa5zgjnokq9676p:
                args:
                    - --run-all
                    - --plot
                    - --save-plot
                    - comparison_wandb.png
                codePath: smart_thermostat_experiments.py
                codePathLocal: smart_thermostat_experiments.py
                executable: /Users/niccolo/Developer/Tesi/Tesi_Active_Inference/venv/bin/python3
                git:
                    commit: b06c2da7ddcf5de230a60db32adb244a6c7a4c63
                    remote: https://github.com/niccoloc0/Tesi_Active_Inference
                host: Niccolos-Mac-mini.local
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/niccolo/Developer/Tesi/Tesi_Active_Inference/smart_thermostat_experiments.py
                python: CPython 3.13.7
                root: /Users/niccolo/Developer/Tesi/Tesi_Active_Inference
                startedAt: "2025-12-16T13:29:40.976409Z"
                writerId: n0jzqf4dz2jyki3iesa5zgjnokq9676p
        m: []
        python_version: 3.13.7
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": darwin-arm64
initial_budget:
    value: 75
mode:
    value: pragmatic_only
seasons_config:
    value:
        Autunno:
            outside_temp: 12
        Estate:
            outside_temp: 35
        Inverno:
            outside_temp: 0
        Primavera:
            outside_temp: 15
seasons_target:
    value:
        Autunno: 20.5
        Estate: 24
        Inverno: 20
        Primavera: 21
simulation_duration:
    value: 300
